### ISSUE TITLE
How to download data and provide it to website

### ISSUE THREAD

**Issue by FelixTe** [ReTtiChDieOrganisation/ReTtiChDasRepo#8]
We need some server with a small drive, which is accessible from outside, which automatically runs a python script every few seconds/minutes. The python script updates the data. Wanted to assign @jac803 but did not work

**Comment by jac803** [comment]
Ich teste es mal mit einem Raspberry Pi Zero W V1.1

**Comment by jac803** [comment]
Ich bekomme folgenden Fehler auf dem Raspberry Pi. Jemand ne Idee was das sein könnte?

`(rettich) jacob@raspberrypi:~/ReTtiChDasRepo $ python untitled0.py
Requesting Token...

Requesting Token...

Requesting Token...

Requesting Token...

Requesting Token...

Traceback (most recent call last):
  File "/home/jacob/ReTtiChDasRepo/untitled0.py", line 219, in <module>
    calculate_stats()
  File "/home/jacob/ReTtiChDasRepo/untitled0.py", line 171, in calculate_stats
    shared_segments = [seg['name'] for seg in all_rides[str(group[0])]['segment_efforts']]
                                                            ~~~~~^^^
IndexError: list index out of range
`

**Comment by FelixTe** [comment]
Hört sich nach einem fehler in der untitled0.py an der da eigentlich nicht sein sollte also liegt nicht an dem raspberry pi. Ich gucke da später mal rein

**Comment by Flo1314** [comment]
@FelixTe hat vor ein paar Tagen noch geprahlt dass er die untitled0.py ja ganz alleine geschrieben hat, also ist er da genau der richtige Ansprechpartner ;)

**Comment by FelixTe** [comment]
Zeile 160 ersetzen mit
```
        if id_list_rider !=[]:
            groups.append(id_list_rider)
``` 
Das Problem war das @herrdavidera in den letzten 7 Tagen keine Fahrt gefahren ist

**Comment by herrdavidera** [comment]
Es tut mir Leid

**Comment by FelixTe** [comment]
Hups ausversehen das issue geclost dabei habe ich ja nur auf eine Frage geantwortet

**Comment by FelixTe** [comment]
Ich tagge hier auch mal @Flo1314, weil er das sehr naheliegende issue "wie lade ich json Dateien runter und speichere sie in einer lokalen variable", was deutlich schwieriger als erwartet ist, bearbeitet

**Comment by jac803** [comment]
ToDo's
- [ ] Auf Raspberry Pi Zero W 1.1 via SSH zugreifen
- [ ] Python Umgebung aufsetzen
- [ ] untitled0.py ausführen können
- [ ] Timer zum geregelten Ausführen des Python Skripts
- [ ] Server aufsetzen
- [ ] JSON Dateien über Seever verfügbar machen

**Comment by FelixTe** [comment]
Ich kann das oben rein machen dann sieht man das so cool
